[package]
name = "collapseloader"
version = "0.1.8"
description = "CollapseLoader"
authors = ["dest4590"]
edition = "2021"
build = "build.rs"

[lib]
name = "collapseloader_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.4.0", features = [] }

[dependencies]
tauri = { version = "2.8.4", features = [] }
tauri-plugin-opener = "2.5.0"
tauri-plugin-notification = "2.3.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
colored = "3.0.0"
lazy_static = "1.5.0"
rand = "0.9.2"
reqwest = { version = "0.12.23", features = ["blocking", "json", "stream"] }
semver = "1.0.26"
zip = "4.5.0"
tokio = { version = "1.47.1", features = ["macros"] }
roxmltree = "0.20.0"
opener = "0.8.2"
uuid = { version = "1.18.0", features = ["v4"] }
chrono = { version = "0.4.41", features = ["serde"] }
paste = "1.0.15"
open = "5.3.2"
md5 = "0.8.0"
discord-rich-presence = "0.2.5"
futures-util = "0.3.31"
futures = "0.3.31"
base64 = "0.22.1"
tauri-plugin-dialog = "2.3.3"

[target.'cfg(windows)'.dependencies]
winreg = { version = "0.55.0" }
win-msgbox = { version = "0.2.1" }

[profile.release.package.wry]
debug = true
debug-assertions = true
